### ISSUE TITLE
Bash script to run the powershell file

### ISSUE THREAD

**Issue by CptMonac** [Matticusau/SqlWorkloadGenerator#2]
After a couple of run-ins with the Execution policy warning in Powershell, I found it was helplful to create a bash script that would run the powershell file and exit. Adding this here in case it would be helpful to anyone else.

```
@setlocal
@echo off

REM 
REM  Script to simulate workload on SQL Server
REM

SET ScriptsDirectory=%~dp0
SET PowershellPath=%ScriptsDirectory%RunWorkload.ps1

powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '%PowershellPath%'";

endlocal
```

**Comment by Matticusau** [comment]
Thanks for your contribution.
I don't really like suggesting people run ExecutionPolicy in ByPass but I will be updating the ReadMe.md with similar information as I generally also use a CMD file to run multiple workloads against a single server via powershell.exe and like you have raised it will be worth advising people how to set the ExecutionPolicy to either RemoteSigned or Unrestricted for the process.

Thanks again for raising this.
